spring:
  application:
    name: paint-man

  datasource:
    url: jdbc:mysql://localhost:3306/paint_man
    username: root
    password: zaq1@WSXcde3
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: paint_man
     

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true   

logging:
  file:
    name: paint_man.log
    path: log    

 
    

